export const UPLOAD_IMAGES_START = "UPLOAD_IMAGES_START";
export const UPLOAD_IMAGES_SUCCESS = "UPLOAD_IMAGES_SUCCESS";
export const UPLOAD_IMAGES_FAIL = "UPLOAD_IMAGES_FAIL";
export const UPLOAD_IMAGES_TO_DB_SUCCESS = "UPLOAD_IMAGES_TO_DB_SUCCESS";