export const GET_ROADMAP_CONTENT_START = "GET_ROADMAP_CONTENT_START";
export const GET_ROADMAP_CONTENT_SUCCESS = "GET_ROADMAP_CONTENT_SUCCESS";
export const GET_ROADMAP_CONTENT_FAIL = "GET_ROADMAP_CONTENT_FAIL";