export const GET_COLLECTIONS_CONTENT_START = "GET_COLLECTIONS_CONTENT_START";
export const GET_COLLECTIONS_CONTENT_SUCCESS = "GET_COLLECTIONS_CONTENT_SUCCESS";
export const GET_COLLECTIONS_CONTENT_FAIL = "GET_COLLECTIONS_CONTENT_FAIL";