export const GET_BANNER_CONTENT_START = "GET_BANNER_CONTENT_START";
export const GET_BANNER_CONTENT_SUCCESS = "GET_BANNER_CONTENT_SUCCESS";
export const GET_BANNER_CONTENT_FAIL = "GET_BANNER_CONTENT_FAIL";