export const GET_WELCOME_CONTENT_START = "GET_WELCOME_CONTENT_START";
export const GET_WELCOME_CONTENT_SUCCESS = "GET_WELCOME_CONTENT_SUCCESS";
export const GET_WELCOME_CONTENT_FAIL = "GET_WELCOME_CONTENT_FAIL";